# Generated by Django 3.1.7 on 2021-03-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khoroch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
